--- 
abstract: consume data from multiple sources, best first; om nom nom!
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 0.005
license: perl
name: Data-InputMonster
requires: 
  Carp: 0
  Sub::Exporter: 0
version: 0.002
